version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared_net

volumes:
  mysql_data:

networks:
  shared_net:
    name: shared_net
    driver: bridge